// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TemplateProject.WebTests.Features
{
    using TechTalk.SpecFlow;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class EmailTemplateFeature
    {

        private static TechTalk.SpecFlow.ITestRunner testRunner;

#line 1 "EmailTemplate.feature"
#line hidden

        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Email Template", "\tIn order to send out thank you and follow up emails to donors\r\n\tAs a Milk Bank U" +
                    "ser\r\n\tI want to be able to add, edit, and delete Email Templates", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null)
                        && (testRunner.FeatureContext.FeatureInfo.Title != "Email Template")))
            {
                TemplateProject.WebTests.Features.EmailTemplateFeature.FeatureSetup(null);
            }
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }

        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }

        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.10.1\tUser can add new Thank You email templates. Include templates for the foll" +
            "owing Milk Banks")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Email Template")]
        public virtual void _5_10_1UserCanAddNewThankYouEmailTemplates_IncludeTemplatesForTheFollowingMilkBanks()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.10.1\tUser can add new Thank You email templates. Include templates for the foll" +
                    "owing Milk Banks", ((string[])(null)));
#line 6
            this.ScenarioSetup(scenarioInfo);
#line 7
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
            testRunner.When("user navigates to Email Templates", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
            testRunner.And("element with id btnAddEmailTemplate is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
            testRunner.And("dropdown with id TemplateType value Thank You Letter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
            testRunner.And("dropdown with id TemplateMilkBank value Tiny Treasures Milk Bank", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
            testRunner.And("text Test TTB Thank You entered in TemplateTitle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
            testRunner.And("text TTTBTY entered in ShortTitle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
            testRunner.And("text Test Subject entered in TemplateSubject", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
            testRunner.And("text Test Body entered in TemplateBody", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
            testRunner.And("text Test Signature entered in TemplateSignature", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
            testRunner.And("element with class k-grid-update is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
            testRunner.Then("the 1 column in row containing Test TTB Thank You text in EmailTemplate grid shou" +
                               "ld be Tiny Treasures Milk Bank", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 19
            testRunner.Then("the 3 column in row containing Test TTB Thank You text in EmailTemplate grid shou" +
                               "ld be Thank You Letter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 20
            testRunner.When("email template deleted Test TTB Thank You", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 21
            testRunner.Then("the number of rows in grid EmailTemplate should be 0", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.10.2\tEdit function is available for each of the Thank You email templates")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Email Template")]
        public virtual void _5_10_2EditFunctionIsAvailableForEachOfTheThankYouEmailTemplates()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.10.2\tEdit function is available for each of the Thank You email templates", ((string[])(null)));
#line 23
            this.ScenarioSetup(scenarioInfo);
#line 24
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 25
            testRunner.When("thank you email template created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 26
            testRunner.And("element with class k-grid-edit clicked in EmailTemplate grid with row containing " +
                               "text Test TTB Thank You", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
            testRunner.And("dropdown with id TemplateType value HH Follow Up", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
            testRunner.And("dropdown with id TemplateMilkBank value Helping Hands (Komen) Milk Bank", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
            testRunner.And("text Test HH Follow Up entered in TemplateTitle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
            testRunner.And("text THHFU entered in ShortTitle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
            testRunner.And("element with class k-grid-update is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
            testRunner.Then("the 1 column in row containing Test HH Follow Up text in EmailTemplate grid shoul" +
                               "d be Helping Hands (Komen) Milk Bank", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 33
            testRunner.Then("the 3 column in row containing Test HH Follow Up text in EmailTemplate grid shoul" +
                               "d be HH Follow Up", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 34
            testRunner.When("email template deleted Test HH Follow Up", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 35
            testRunner.Then("the number of rows in grid EmailTemplate should be 0", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.10.2.1 A function to activate the email template")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Email Template")]
        public virtual void _5_10_2_1AFunctionToActivateTheEmailTemplate()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.10.2.1 A function to activate the email template", ((string[])(null)));
#line 37
            this.ScenarioSetup(scenarioInfo);
#line 38
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 39
            testRunner.When("user navigates to Email Templates", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 40
            testRunner.And("element with id btnAddEmailTemplate is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 41
            testRunner.And("dropdown with id TemplateType value Thank You Letter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 42
            testRunner.And("dropdown with id TemplateMilkBank value Tiny Treasures Milk Bank", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 43
            testRunner.And("text Test TTB Thank You entered in TemplateTitle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 44
            testRunner.And("text TTTBTY entered in ShortTitle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 45
            testRunner.And("element with id TemplateActive is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 46
            testRunner.And("text Test Subject entered in TemplateSubject", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 47
            testRunner.And("text Test Body entered in TemplateBody", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
            testRunner.And("text Test Signature entered in TemplateSignature", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 49
            testRunner.And("element with class k-grid-update is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 50
            testRunner.Then("the 1 column in row containing Test TTB Thank You text in EmailTemplate grid shou" +
                               "ld be Tiny Treasures Milk Bank", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 51
            testRunner.Then("the 3 column in row containing Test TTB Thank You text in EmailTemplate grid shou" +
                               "ld be Thank You Letter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 52
            testRunner.Then("the 4 column in row containing Test TTB Thank You text in EmailTemplate grid shou" +
                               "ld be Yes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 53
            testRunner.When("email template deleted Test TTB Thank You", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 54
            testRunner.Then("the number of rows in grid EmailTemplate should be 0", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.10.2.2 A function to set email to send automatically")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Email Template")]
        public virtual void _5_10_2_2AFunctionToSetEmailToSendAutomatically()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.10.2.2 A function to set email to send automatically", ((string[])(null)));
#line 56
            this.ScenarioSetup(scenarioInfo);
#line 57
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 58
            testRunner.When("user navigates to Email Templates", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 59
            testRunner.And("element with id btnAddEmailTemplate is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 60
            testRunner.And("dropdown with id TemplateType value Thank You Letter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 61
            testRunner.And("dropdown with id TemplateMilkBank value Tiny Treasures Milk Bank", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 62
            testRunner.And("text Test TTB Thank You entered in TemplateTitle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 63
            testRunner.And("text TTTBTY entered in ShortTitle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 64
            testRunner.And("element with id AutomaticSend is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 65
            testRunner.And("text Test Subject entered in TemplateSubject", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 66
            testRunner.And("text Test Body entered in TemplateBody", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 67
            testRunner.And("text Test Signature entered in TemplateSignature", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 68
            testRunner.And("element with class k-grid-update is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 69
            testRunner.Then("the 5 column in row containing Test TTB Thank You text in EmailTemplate grid shou" +
                               "ld be Yes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 70
            testRunner.When("email template deleted Test TTB Thank You", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 71
            testRunner.Then("the number of rows in grid EmailTemplate should be 0", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.10.2.3 A function to set number of days for email to be sent automatically")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Email Template")]
        public virtual void _5_10_2_3AFunctionToSetNumberOfDaysForEmailToBeSentAutomatically()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.10.2.3 A function to set number of days for email to be sent automatically", ((string[])(null)));
#line 73
            this.ScenarioSetup(scenarioInfo);
#line 74
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 75
            testRunner.When("user navigates to Email Templates", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 76
            testRunner.And("element with id btnAddEmailTemplate is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 77
            testRunner.And("dropdown with id TemplateType value HH Follow Up", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 78
            testRunner.And("dropdown with id TemplateMilkBank value Helping Hands (Komen) Milk Bank", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 79
            testRunner.And("text Test HH Follow Up entered in TemplateTitle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 80
            testRunner.And("text THHFU entered in ShortTitle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 81
            testRunner.And("element with id AutomaticSend is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 82
            testRunner.And("value 5 entered in numeric with DaysFromLeadToSend id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 83
            testRunner.And("text Test Subject entered in TemplateSubject", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 84
            testRunner.And("text Test Body entered in TemplateBody", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 85
            testRunner.And("text Test Signature entered in TemplateSignature", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 86
            testRunner.And("element with class k-grid-update is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 87
            testRunner.Then("the 6 column in row containing Test HH Follow Up text in EmailTemplate grid shoul" +
                               "d be 5", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 88
            testRunner.When("email template deleted Test HH Follow Up", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 89
            testRunner.Then("the number of rows in grid EmailTemplate should be 0", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
