// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TemplateProject.WebTests.Features
{
    using TechTalk.SpecFlow;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class GeneralShippingProcessFulFillingAndVerifyingOrdersFeature
    {

        private static TechTalk.SpecFlow.ITestRunner testRunner;

#line 1 "GeneralShippingProcessFulFillingAndVerifyingOrders.feature"
#line hidden

        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "General Shipping Process FulFilling And Verifying Orders", "\tIn order to ship pump/supply and cooler orders\r\n\tAs a Milk Bank User or Warehous" +
                    "e user\r\n\tI want to be able to fulfill and verify orders", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null)
                        && (testRunner.FeatureContext.FeatureInfo.Title != "General Shipping Process FulFilling And Verifying Orders")))
            {
                TemplateProject.WebTests.Features.GeneralShippingProcessFulFillingAndVerifyingOrdersFeature.FeatureSetup(null);
            }
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }

        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }

        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.7.1.1 View outstanding orders not fulfilled by filtering status to “pending”")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "General Shipping Process FulFilling And Verifying Orders")]
        public virtual void _5_7_1_1ViewOutstandingOrdersNotFulfilledByFilteringStatusToPending()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.7.1.1 View outstanding orders not fulfilled by filtering status to “pending”", ((string[])(null)));
#line 6
            this.ScenarioSetup(scenarioInfo);
#line 7
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
            testRunner.When("cooler order is created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
            testRunner.And("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
            testRunner.And("element with id coolerTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
            testRunner.Then("element coolerTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 12
            testRunner.When("filter Pending in column Status in grid coolerOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 13
            testRunner.Then("the 10 column in 1 row in coolerOrdersGrid grid should be Pending", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 14
            testRunner.When("pump order created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 15
            testRunner.And("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
            testRunner.When("element with id pumpSupplyTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 17
            testRunner.Then("element pumpSupplyTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 18
            testRunner.When("filter Pending in column Status in grid pumpOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 19
            testRunner.Then("the 10 column in 1 row in pumpOrdersGrid grid should be Pending", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.7.1.2 User can select multiple orders and print Cooler Packets, Bag Packets, Pa" +
            "cking Slip. A total number of selected orders display")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "General Shipping Process FulFilling And Verifying Orders")]
        public virtual void _5_7_1_2UserCanSelectMultipleOrdersAndPrintCoolerPacketsBagPacketsPackingSlip_ATotalNumberOfSelectedOrdersDisplay()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.7.1.2 User can select multiple orders and print Cooler Packets, Bag Packets, Pa" +
                    "cking Slip. A total number of selected orders display", ((string[])(null)));
#line 22
            this.ScenarioSetup(scenarioInfo);
#line 23
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 24
            testRunner.When("cooler order is created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 25
            testRunner.And("cooler order is created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
            testRunner.And("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
            testRunner.And("filter Pending in column Status in grid coolerOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
            testRunner.And("row containing text Pending in grid coolerOrdersGrid is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
            testRunner.Then("element with id printPackets has value Print Cooler Packets (2)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 30
            testRunner.When("element with id printPackets is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 31
            testRunner.And("switch to new tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
            testRunner.Then("the page Order/CoolerPacket should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 33
            testRunner.When("switch to old tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 34
            testRunner.And("pump order created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 35
            testRunner.And("pump order created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
            testRunner.And("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
            testRunner.And("element with id pumpSupplyTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
            testRunner.Then("element pumpSupplyTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 39
            testRunner.When("filter No in column BagOnlyName in grid pumpOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 40
            testRunner.Then("the 11 column in 1 row in pumpOrdersGrid grid should be No", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 41
            testRunner.When("row containing text No in grid pumpOrdersGrid is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 42
            testRunner.Then("element with id printPackingSlips has value Print Packing Slips (2)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 43
            testRunner.When("element with id printPackingSlips is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 44
            testRunner.And("switch to new tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 45
            testRunner.Then("the page Order/PackingSlip should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 46
            testRunner.When("switch to old tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 47
            testRunner.And("bag only order created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
            testRunner.And("bag only order created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 49
            testRunner.And("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 50
            testRunner.When("element with id pumpSupplyTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 51
            testRunner.Then("element pumpSupplyTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 52
            testRunner.When("filter Yes in column BagOnlyName in grid pumpOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 53
            testRunner.Then("the 11 column in 1 row in pumpOrdersGrid grid should be Yes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 54
            testRunner.When("row containing text Yes in grid pumpOrdersGrid is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 55
            testRunner.Then("element with id printPackingSlips has value Print Packing Slips (2)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 56
            testRunner.When("element with id printPackingSlips is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 57
            testRunner.And("switch to new tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
            testRunner.And("scroll to bottom of screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
            testRunner.Then("the page Order/PackingSlip should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.7.1.3 The “fulfill” function is available for fulfillment process, which apply " +
            "to Coolers and Pump Supply orders")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "General Shipping Process FulFilling And Verifying Orders")]
        public virtual void _5_7_1_3TheFulfillFunctionIsAvailableForFulfillmentProcessWhichApplyToCoolersAndPumpSupplyOrders()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.7.1.3 The “fulfill” function is available for fulfillment process, which apply " +
                    "to Coolers and Pump Supply orders", ((string[])(null)));
#line 61
            this.ScenarioSetup(scenarioInfo);
#line 62
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 63
            testRunner.When("cooler order is created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 64
            testRunner.And("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 65
            testRunner.And("filter Pending in column Status in grid coolerOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 66
            testRunner.And("element with class k-grid-Fulfill clicked in coolerOrdersGrid grid with row conta" +
                               "ining text Pending", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 67
            testRunner.Then("the page Order/Step1 should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 68
            testRunner.When("radiobutton with id ShippingMethod_Ground is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 69
            testRunner.And("text 1223-3344-4455 entered in TrackingNumber", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 70
            testRunner.And("element with id btnSubmitFulfillment is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 71
            testRunner.Then("the page Order/Step2 should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 72
            testRunner.When("text 9988-7766-5544 entered in ReturnTrackingNumber", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 73
            testRunner.And("element with id btnSubmitFulfillment is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 74
            testRunner.Then("the page Order/Step3 should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 75
            testRunner.When("element with id btnOrderManagement is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 76
            testRunner.Then("the page Orders should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 77
            testRunner.When("pump order created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 78
            testRunner.And("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 79
            testRunner.And("element with id pumpSupplyTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 80
            testRunner.Then("element pumpSupplyTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 81
            testRunner.When("filter Pending in column Status in grid pumpOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 82
            testRunner.When("filter No in column BagOnlyName in grid pumpOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 83
            testRunner.And("element with class k-grid-Fulfill clicked in pumpOrdersGrid grid with row contain" +
                               "ing text Pending", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 84
            testRunner.Then("the page Order/Step1 should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 85
            testRunner.When("radiobutton with id ShippingMethod_Ground is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 86
            testRunner.And("text 1223-3344-4455 entered in TrackingNumber", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 87
            testRunner.And("element with id btnSubmitFulfillment is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 88
            testRunner.Then("the page Order/Step2 should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 89
            testRunner.When("text 9988-7766-5544 entered in ReturnTrackingNumber", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 90
            testRunner.And("element with id btnSubmitFulfillment is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 91
            testRunner.Then("the page Order/Step3 should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 92
            testRunner.When("element with id btnOrderManagement is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 93
            testRunner.Then("the page Orders should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.7.1.4 The “Confirm” function is available for fulfillment process, which apply " +
            "to Bag Only orders")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "General Shipping Process FulFilling And Verifying Orders")]
        public virtual void _5_7_1_4TheConfirmFunctionIsAvailableForFulfillmentProcessWhichApplyToBagOnlyOrders()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.7.1.4 The “Confirm” function is available for fulfillment process, which apply " +
                    "to Bag Only orders", ((string[])(null)));
#line 95
            this.ScenarioSetup(scenarioInfo);
#line 96
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 97
            testRunner.When("user navigates to add pump supply order page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 98
            testRunner.And("text 60002 entered in Order_DonorID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 99
            testRunner.And("element with id updateDonorInfo is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 100
            testRunner.Then("the dropdown MilkBank has selected value Tiny Treasures Milk Bank", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 101
            testRunner.Then("element with id FirstName has value Erin", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 102
            testRunner.Then("element with id LastName has value Povich", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 103
            testRunner.Then("element with id Street has value 309 Cimarron Valley Trail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 104
            testRunner.Then("element with id State has value MO", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 105
            testRunner.Then("element with id ZipCode has value 63385", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 106
            testRunner.Then("element with id Email has value erinpovich@yahoo.com", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 107
            testRunner.Then("element with id PhoneNumber has value (314)-803-6875", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 108
            testRunner.Then("the dropdown Order_ShippingMethod has selected value Ground", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 109
            testRunner.When("value 5 entered in numeric with Bags id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 110
            testRunner.And("text Test Bag Only Order entered in Order_Notes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 111
            testRunner.And("element with id btnPlaceOrder is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 112
            testRunner.Then("the page Order/OrderDetail should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 113
            testRunner.When("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 114
            testRunner.When("element with id pumpSupplyTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 115
            testRunner.Then("element pumpSupplyTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 116
            testRunner.When("filter Yes in column BagOnlyName in grid pumpOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 117
            testRunner.And("element with class k-grid-Confirm clicked in pumpOrdersGrid grid with row contain" +
                               "ing text 60002", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 118
            testRunner.Then("the kendo alert text should be Are you sure that you want to confirm this bag ord" +
                               "er?", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 119
            testRunner.When("click kendo alert box ok true", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 120
            testRunner.Then("the 10 column in 1 row in pumpOrdersGrid grid should be OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.7.1.5 Order page displays order details")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "General Shipping Process FulFilling And Verifying Orders")]
        public virtual void _5_7_1_5OrderPageDisplaysOrderDetails()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.7.1.5 Order page displays order details", ((string[])(null)));
#line 122
            this.ScenarioSetup(scenarioInfo);
#line 123
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 124
            testRunner.When("cooler order is created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 125
            testRunner.And("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 126
            testRunner.And("element with class k-i-expand clicked in coolerOrdersGrid grid with row containin" +
                               "g text Fulfilled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 127
            testRunner.Then("element with class orders is visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 128
            testRunner.When("element with id CoolerShippingTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 129
            testRunner.Then("element CoolerShippingTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 130
            testRunner.When("pump order created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 131
            testRunner.And("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 132
            testRunner.When("element with id pumpSupplyTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 133
            testRunner.Then("element pumpSupplyTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 134
            testRunner.When("element with class k-i-expand clicked in pumpOrdersGrid grid with row containing " +
                               "text No", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 135
            testRunner.Then("element with id PumpOrderItemsTab is visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 136
            testRunner.When("element with id PumpShippingTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 137
            testRunner.Then("element PumpShippingTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.7.1.6 Once fulfilled, Cooler Orders shall have a status of “Fulfilled”")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "General Shipping Process FulFilling And Verifying Orders")]
        public virtual void _5_7_1_6OnceFulfilledCoolerOrdersShallHaveAStatusOfFulfilled()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.7.1.6 Once fulfilled, Cooler Orders shall have a status of “Fulfilled”", ((string[])(null)));
#line 139
            this.ScenarioSetup(scenarioInfo);
#line 140
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 141
            testRunner.When("cooler order is created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 142
            testRunner.When("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 143
            testRunner.When("filter Pending in column Status in grid coolerOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 144
            testRunner.And("element with class k-grid-Fulfill clicked in coolerOrdersGrid grid with row conta" +
                               "ining text Pending", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 145
            testRunner.Then("the page Order/Step1 should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 146
            testRunner.When("radiobutton with id ShippingMethod_Ground is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 147
            testRunner.And("text 1223-3344-4455 entered in TrackingNumber", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 148
            testRunner.And("element with id btnSubmitFulfillment is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 149
            testRunner.Then("the page Order/Step2 should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 150
            testRunner.When("text 9988-7766-5544 entered in ReturnTrackingNumber", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 151
            testRunner.And("element with id btnSubmitFulfillment is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 152
            testRunner.Then("the page Order/Step3 should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 153
            testRunner.When("element with id btnOrderManagement is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 154
            testRunner.Then("the page Orders should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 155
            testRunner.When("filter Fulfilled in column Status in grid coolerOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 156
            testRunner.Then("the 10 column in row containing 60002 text in coolerOrdersGrid grid should be Ful" +
                               "filled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.7.1.7 Once fulfilled, Pump/Supply/Bag Only Orders shall have a status of “OK”")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "General Shipping Process FulFilling And Verifying Orders")]
        public virtual void _5_7_1_7OnceFulfilledPumpSupplyBagOnlyOrdersShallHaveAStatusOfOK()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.7.1.7 Once fulfilled, Pump/Supply/Bag Only Orders shall have a status of “OK”", ((string[])(null)));
#line 158
            this.ScenarioSetup(scenarioInfo);
#line 159
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 160
            testRunner.When("user navigates to add pump supply order page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 161
            testRunner.And("text 60002 entered in Order_DonorID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 162
            testRunner.And("element with id updateDonorInfo is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 163
            testRunner.Then("the dropdown MilkBank has selected value Tiny Treasures Milk Bank", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 164
            testRunner.Then("element with id FirstName has value Erin", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 165
            testRunner.Then("element with id LastName has value Povich", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 166
            testRunner.Then("element with id Street has value 309 Cimarron Valley Trail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 167
            testRunner.Then("element with id State has value MO", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 168
            testRunner.Then("element with id ZipCode has value 63385", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 169
            testRunner.Then("element with id Email has value erinpovich@yahoo.com", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 170
            testRunner.Then("element with id PhoneNumber has value (314)-803-6875", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 171
            testRunner.Then("the dropdown Order_ShippingMethod has selected value Ground", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 172
            testRunner.When("value 1 entered in numeric with DoublePumpingKit id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 173
            testRunner.And("value 1 entered in numeric with 24mmBreastshields id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 174
            testRunner.And("value 1 entered in numeric with 27mmBreastshields id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 175
            testRunner.And("value 1 entered in numeric with 30mmBreastshields id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 176
            testRunner.And("value 1 entered in numeric with 8ozBottlesSet id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 177
            testRunner.And("value 1 entered in numeric with PersonalFitConnectors id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 178
            testRunner.And("value 1 entered in numeric with ValvesandMembranes id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 179
            testRunner.And("value 1 entered in numeric with Membranes id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 180
            testRunner.And("value 1 entered in numeric with Tubing id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 181
            testRunner.And("value 1 entered in numeric with Bags id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 182
            testRunner.And("value 1 entered in numeric with YellowBag id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 183
            testRunner.And("value 1 entered in numeric with 24mmBreastshields id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 184
            testRunner.And("text Test Note entered in Order_Notes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 185
            testRunner.And("element with id btnPlaceOrder is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 186
            testRunner.Then("the page Order/OrderDetail should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 187
            testRunner.When("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 188
            testRunner.When("element with id pumpSupplyTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 189
            testRunner.Then("element pumpSupplyTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 190
            testRunner.When("filter Pending in column Status in grid pumpOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 191
            testRunner.And("element with class k-grid-Fulfill clicked in pumpOrdersGrid grid with row contain" +
                               "ing text Pending", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 192
            testRunner.Then("the page Order/Step1 should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 193
            testRunner.When("radiobutton with id ShippingMethod_Ground is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 194
            testRunner.And("text 1223-3344-4455 entered in TrackingNumber", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 195
            testRunner.And("element with id btnSubmitFulfillment is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 196
            testRunner.Then("the page Order/Step2 should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 197
            testRunner.When("text 9988-7766-5544 entered in ReturnTrackingNumber", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 198
            testRunner.And("element with id btnSubmitFulfillment is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 199
            testRunner.Then("the page Order/Step3 should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 200
            testRunner.When("element with id btnOrderManagement is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 201
            testRunner.Then("the page Orders should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 202
            testRunner.When("filter OK in column Status in grid pumpOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 203
            testRunner.Then("the 10 column in row containing 60002 text in pumpOrdersGrid grid should be OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.7.2 Verifying Orders apply to only Cooler Orders")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "General Shipping Process FulFilling And Verifying Orders")]
        public virtual void _5_7_2VerifyingOrdersApplyToOnlyCoolerOrders()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.7.2 Verifying Orders apply to only Cooler Orders", ((string[])(null)));
#line 205
            this.ScenarioSetup(scenarioInfo);
#line 206
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 207
            testRunner.When("cooler order is created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 208
            testRunner.When("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 209
            testRunner.And("cooler order fulfilled 60002", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 210
            testRunner.And("user logs out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 211
            testRunner.Given("Username MbtsWHTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 212
            testRunner.When("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 213
            testRunner.And("filter Fulfilled in column Status in grid coolerOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 214
            testRunner.And("element with class k-grid-Verify clicked in coolerOrdersGrid grid with row contai" +
                               "ning text Fulfilled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 215
            testRunner.Then("the page Order/Verify should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 216
            testRunner.When("element with id btnSubmitVerification is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 217
            testRunner.Then("the page Order/Verified should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 218
            testRunner.When("element with id btnOrderManagement is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 219
            testRunner.Then("the page Orders should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 220
            testRunner.When("filter OK in column Status in grid coolerOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 221
            testRunner.Then("the 10 column in row containing 60002 text in coolerOrdersGrid grid should be OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.7.2.1 User cannot verify his her own fulfilled order.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "General Shipping Process FulFilling And Verifying Orders")]
        public virtual void _5_7_2_1UserCannotVerifyHisHerOwnFulfilledOrder_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.7.2.1 User cannot verify his her own fulfilled order.", ((string[])(null)));
#line 223
            this.ScenarioSetup(scenarioInfo);
#line 224
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 225
            testRunner.When("cooler order is created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 226
            testRunner.When("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 227
            testRunner.And("cooler order fulfilled 60002", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 228
            testRunner.And("filter Fulfilled in column Status in grid coolerOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 229
            testRunner.And("element with class k-grid-Verify clicked in coolerOrdersGrid grid with row contai" +
                               "ning text mbtsmbtester1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 230
            testRunner.Then("the page Order/Verify should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 231
            testRunner.When("element with id btnCancel is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 232
            testRunner.Then("the page Orders should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 233
            testRunner.When("filter Fulfilled in column Status in grid coolerOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 234
            testRunner.Then("the 10 column in row containing 60002 text in coolerOrdersGrid grid should be Ful" +
                               "filled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.7.2.2 Allow user to view outstanding orders that were not verified by filtering" +
            " the status to “fulfilled”.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "General Shipping Process FulFilling And Verifying Orders")]
        public virtual void _5_7_2_2AllowUserToViewOutstandingOrdersThatWereNotVerifiedByFilteringTheStatusToFulfilled_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.7.2.2 Allow user to view outstanding orders that were not verified by filtering" +
                    " the status to “fulfilled”.", ((string[])(null)));
#line 236
            this.ScenarioSetup(scenarioInfo);
#line 237
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 238
            testRunner.When("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 239
            testRunner.And("filter Fulfilled in column Status in grid coolerOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 240
            testRunner.Then("the 10 column in 1 row in coolerOrdersGrid grid should be Fulfilled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.7.2.3 User can click “verify” to each order to navigate to Order Verification")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "General Shipping Process FulFilling And Verifying Orders")]
        public virtual void _5_7_2_3UserCanClickVerifyToEachOrderToNavigateToOrderVerification()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.7.2.3 User can click “verify” to each order to navigate to Order Verification", ((string[])(null)));
#line 242
            this.ScenarioSetup(scenarioInfo);
#line 243
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 244
            testRunner.When("cooler order is created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 245
            testRunner.When("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 246
            testRunner.And("cooler order fulfilled 60002", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 247
            testRunner.And("user logs out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 248
            testRunner.Given("Username MbtsWHTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 249
            testRunner.When("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 250
            testRunner.And("filter Fulfilled in column Status in grid coolerOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 251
            testRunner.And("element with class k-grid-Verify clicked in coolerOrdersGrid grid with row contai" +
                               "ning text Fulfilled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 252
            testRunner.Then("the page Order/Verify should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.7.2.4 Once verified, an order shall have a status “OK”. Upon confirmation, this" +
            " will update shipping date.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "General Shipping Process FulFilling And Verifying Orders")]
        public virtual void _5_7_2_4OnceVerifiedAnOrderShallHaveAStatusOK_UponConfirmationThisWillUpdateShippingDate_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.7.2.4 Once verified, an order shall have a status “OK”. Upon confirmation, this" +
                    " will update shipping date.", ((string[])(null)));
#line 254
            this.ScenarioSetup(scenarioInfo);
#line 255
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 256
            testRunner.When("cooler order is created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 257
            testRunner.When("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 258
            testRunner.And("cooler order fulfilled 60002", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 259
            testRunner.And("user logs out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 260
            testRunner.Given("Username MbtsWHTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 261
            testRunner.When("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 262
            testRunner.And("filter Fulfilled in column Status in grid coolerOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 263
            testRunner.And("element with class k-grid-Verify clicked in coolerOrdersGrid grid with row contai" +
                               "ning text Fulfilled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 264
            testRunner.Then("the page Order/Verify should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 265
            testRunner.When("element with id btnSubmitVerification is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 266
            testRunner.Then("the page Order/Verified should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 267
            testRunner.When("element with id btnOrderManagement is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 268
            testRunner.Then("the page Orders should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 269
            testRunner.When("filter OK in column Status in grid coolerOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 270
            testRunner.Then("the 10 column in row containing 60002 text in coolerOrdersGrid grid should be OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
