// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TemplateProject.WebTests.Features
{
    using TechTalk.SpecFlow;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class FRSReq5_1DonorPumpOrderManagementFeature
    {

        private static TechTalk.SpecFlow.ITestRunner testRunner;

#line 1 "OrderCreationDonorPumpSupply.feature"
#line hidden

        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "FRS Req 5.1 Donor Pump Order Management", "\tIn order to order pumps and supplies for donors\r\n\tAs amilk bank usder\r\n\tI want t" +
                    "o be able to create orders for donors containing a pump and supplies.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null)
                        && (testRunner.FeatureContext.FeatureInfo.Title != "FRS Req 5.1 Donor Pump Order Management")))
            {
                TemplateProject.WebTests.Features.FRSReq5_1DonorPumpOrderManagementFeature.FeatureSetup(null);
            }
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }

        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }

        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.1.1.1 The system shall display a count of available pumps.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "FRS Req 5.1 Donor Pump Order Management")]
        public virtual void _5_1_1_1TheSystemShallDisplayACountOfAvailablePumps_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.1.1.1 The system shall display a count of available pumps.", ((string[])(null)));
#line 6
            this.ScenarioSetup(scenarioInfo);
#line 7
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
            testRunner.When("element with id menuInventory is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
            testRunner.And("element with id menuPumps is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
            testRunner.Then("the page Inventory/Pumps should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 11
            testRunner.When("text Available entered in pumpSearchBox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
            testRunner.Then("element with class k-pager-info contains text 1 - 15 of", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.1.1.2 Create Add an Order")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "FRS Req 5.1 Donor Pump Order Management")]
        public virtual void _5_1_1_2CreateAddAnOrder()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.1.1.2 Create Add an Order", ((string[])(null)));
#line 14
            this.ScenarioSetup(scenarioInfo);
#line 15
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 16
            testRunner.When("new pump added", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 17
            testRunner.And("user navigates to add pump supply order page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
            testRunner.And("text 60002 entered in Order_DonorID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
            testRunner.And("element with id updateDonorInfo is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 20
            testRunner.Then("the dropdown MilkBank has selected value Tiny Treasures Milk Bank", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 21
            testRunner.Then("element with id FirstName has value Erin", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 22
            testRunner.Then("element with id LastName has value Povich", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 23
            testRunner.Then("element with id Street has value 309 Cimarron Valley Trail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 24
            testRunner.Then("element with id State has value MO", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 25
            testRunner.Then("element with id ZipCode has value 63385", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 26
            testRunner.Then("element with id Email has value erinpovich@yahoo.com", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 27
            testRunner.Then("element with id PhoneNumber has value (314)-803-6875", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 28
            testRunner.Then("the dropdown Order_ShippingMethod has selected value Ground", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 29
            testRunner.When("element with id showPump is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
            testRunner.And("text 987654321 entered in PumpSerial", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
            testRunner.And("value 1 entered in numeric with DoublePumpingKit id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
            testRunner.And("value 1 entered in numeric with 24mmBreastshields id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
            testRunner.And("value 1 entered in numeric with 27mmBreastshields id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
            testRunner.And("value 1 entered in numeric with 30mmBreastshields id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 35
            testRunner.And("value 1 entered in numeric with 8ozBottlesSet id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
            testRunner.And("value 1 entered in numeric with PersonalFitConnectors id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
            testRunner.And("value 1 entered in numeric with ValvesandMembranes id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
            testRunner.And("value 1 entered in numeric with Membranes id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 39
            testRunner.And("value 1 entered in numeric with Tubing id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
            testRunner.And("value 1 entered in numeric with Bags id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 41
            testRunner.And("value 1 entered in numeric with YellowBag id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 42
            testRunner.And("text Test Note entered in Order_Notes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 43
            testRunner.And("element with id btnPlaceOrder is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 44
            testRunner.Then("the page Order/OrderDetail should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.1.1.2.1 The user can enter Donor ID to pre-populate name address email phone Mi" +
            "lk Bank")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "FRS Req 5.1 Donor Pump Order Management")]
        public virtual void _5_1_1_2_1TheUserCanEnterDonorIDToPre_PopulateNameAddressEmailPhoneMilkBank()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.1.1.2.1 The user can enter Donor ID to pre-populate name address email phone Mi" +
                    "lk Bank", ((string[])(null)));
#line 46
            this.ScenarioSetup(scenarioInfo);
#line 47
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 48
            testRunner.When("user navigates to add pump supply order page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 49
            testRunner.And("text 60002 entered in Order_DonorID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 50
            testRunner.And("element with id updateDonorInfo is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
            testRunner.Then("the dropdown MilkBank has selected value Tiny Treasures Milk Bank", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 52
            testRunner.Then("element with id FirstName has value Erin", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 53
            testRunner.Then("element with id LastName has value Povich", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 54
            testRunner.Then("element with id Street has value 309 Cimarron Valley Trail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 55
            testRunner.Then("element with id State has value MO", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 56
            testRunner.Then("element with id ZipCode has value 63385", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 57
            testRunner.Then("element with id Email has value erinpovich@yahoo.com", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 58
            testRunner.Then("element with id PhoneNumber has value (314)-803-6875", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.1.1.2.2 If Donor ID is blank, the user can manually enter the name address emai" +
            "l phone Milk Bank.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "FRS Req 5.1 Donor Pump Order Management")]
        public virtual void _5_1_1_2_2IfDonorIDIsBlankTheUserCanManuallyEnterTheNameAddressEmailPhoneMilkBank_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.1.1.2.2 If Donor ID is blank, the user can manually enter the name address emai" +
                    "l phone Milk Bank.", ((string[])(null)));
#line 60
            this.ScenarioSetup(scenarioInfo);
#line 61
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 62
            testRunner.When("user navigates to add pump supply order page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 63
            testRunner.And("dropdown with id MilkBank value Texas Childrens Hospital Milk Bank", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 64
            testRunner.And("text Joselyn entered in FirstName", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 65
            testRunner.And("text Fiennes entered in LastName", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 66
            testRunner.And("text 1234 Jackson Ave entered in Street", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 67
            testRunner.And("text Los Angeles entered in City", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 68
            testRunner.And("text CT entered in State", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 69
            testRunner.And("text 90000 entered in ZipCode", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 70
            testRunner.And("text jFiennes@pmail.com entered in Email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 71
            testRunner.And("text (789)-456-1235 entered in PhoneNumber", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 72
            testRunner.Then("the dropdown MilkBank has selected value Texas Childrens Hospital Milk Bank", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 73
            testRunner.Then("element with id FirstName has value Joselyn", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 74
            testRunner.Then("element with id LastName has value Fiennes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 75
            testRunner.Then("element with id Street has value 1234 Jackson Ave", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 76
            testRunner.Then("element with id City has value Los Angeles", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 77
            testRunner.Then("element with id State has value CT", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 78
            testRunner.Then("element with id ZipCode has value 90000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 79
            testRunner.Then("element with id Email has value jFiennes@pmail.com", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 80
            testRunner.Then("element with id PhoneNumber has value (789)-456-1235", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.1.1.2.3 Order Date automatically loads the date at the time of order creation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "FRS Req 5.1 Donor Pump Order Management")]
        public virtual void _5_1_1_2_3OrderDateAutomaticallyLoadsTheDateAtTheTimeOfOrderCreation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.1.1.2.3 Order Date automatically loads the date at the time of order creation", ((string[])(null)));
#line 82
            this.ScenarioSetup(scenarioInfo);
#line 83
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 84
            testRunner.When("user navigates to add pump supply order page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 85
            testRunner.Then("the date field Order_OrderActualDate has current date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.1.1.2.4 An option to include pump in the order")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "FRS Req 5.1 Donor Pump Order Management")]
        public virtual void _5_1_1_2_4AnOptionToIncludePumpInTheOrder()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.1.1.2.4 An option to include pump in the order", ((string[])(null)));
#line 87
            this.ScenarioSetup(scenarioInfo);
#line 88
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 89
            testRunner.When("user navigates to add pump supply order page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 90
            testRunner.When("element with id showPump is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 91
            testRunner.And("text 1555021 entered in PumpSerial", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 92
            testRunner.Then("element with id PumpSerial has value 1555021", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.1.1.2.5 The user shall be able to add supplies & their quantity in the pump ord" +
            "er")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "FRS Req 5.1 Donor Pump Order Management")]
        public virtual void _5_1_1_2_5TheUserShallBeAbleToAddSuppliesTheirQuantityInThePumpOrder()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.1.1.2.5 The user shall be able to add supplies & their quantity in the pump ord" +
                    "er", ((string[])(null)));
#line 94
            this.ScenarioSetup(scenarioInfo);
#line 95
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 96
            testRunner.When("user navigates to add pump supply order page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 97
            testRunner.And("value 1 entered in numeric with DoublePumpingKit id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 98
            testRunner.And("value 1 entered in numeric with 24mmBreastshields id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 99
            testRunner.And("value 1 entered in numeric with 27mmBreastshields id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 100
            testRunner.And("value 1 entered in numeric with 30mmBreastshields id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 101
            testRunner.And("value 1 entered in numeric with 8ozBottlesSet id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 102
            testRunner.And("value 1 entered in numeric with PersonalFitConnectors id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 103
            testRunner.And("value 1 entered in numeric with ValvesandMembranes id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 104
            testRunner.And("value 1 entered in numeric with Membranes id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 105
            testRunner.And("value 1 entered in numeric with Tubing id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 106
            testRunner.And("value 1 entered in numeric with Bags id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 107
            testRunner.And("value 1 entered in numeric with YellowBag id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 108
            testRunner.Then("numeric with id DoublePumpingKit has value 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 109
            testRunner.Then("numeric with id 24mmBreastshields has value 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 110
            testRunner.Then("numeric with id 27mmBreastshields has value 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 111
            testRunner.Then("numeric with id 30mmBreastshields has value 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 112
            testRunner.Then("numeric with id 8ozBottlesSet has value 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 113
            testRunner.Then("numeric with id PersonalFitConnectors has value 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 114
            testRunner.Then("numeric with id ValvesandMembranes has value 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 115
            testRunner.Then("numeric with id Membranes has value 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 116
            testRunner.Then("numeric with id Tubing has value 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 117
            testRunner.Then("numeric with id Bags has value 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 118
            testRunner.Then("numeric with id Tubing has value 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 119
            testRunner.Then("numeric with id YellowBag has value 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.1.1.2.6 The list of supplies will be displayed as a table with all items and qu" +
            "antity field next to each item")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "FRS Req 5.1 Donor Pump Order Management")]
        public virtual void _5_1_1_2_6TheListOfSuppliesWillBeDisplayedAsATableWithAllItemsAndQuantityFieldNextToEachItem()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.1.1.2.6 The list of supplies will be displayed as a table with all items and qu" +
                    "antity field next to each item", ((string[])(null)));
#line 121
            this.ScenarioSetup(scenarioInfo);
#line 122
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 123
            testRunner.When("element with id menuOrders is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 124
            testRunner.And("element with id menuCreatePump/SupplyOrder is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 125
            testRunner.Then("the page Order/AddPumpSupplyOrder should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.1.1.2.7 Notes field shall be present for the user to enter comments for this or" +
            "der")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "FRS Req 5.1 Donor Pump Order Management")]
        public virtual void _5_1_1_2_7NotesFieldShallBePresentForTheUserToEnterCommentsForThisOrder()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.1.1.2.7 Notes field shall be present for the user to enter comments for this or" +
                    "der", ((string[])(null)));
#line 127
            this.ScenarioSetup(scenarioInfo);
#line 128
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 129
            testRunner.When("user navigates to add pump supply order page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 130
            testRunner.And("text Test Note entered in Order_Notes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 131
            testRunner.Then("element with id Order_Notes has value Test Note", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.1.1.2.8 The user can select shipping methods")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "FRS Req 5.1 Donor Pump Order Management")]
        public virtual void _5_1_1_2_8TheUserCanSelectShippingMethods()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.1.1.2.8 The user can select shipping methods", ((string[])(null)));
#line 133
            this.ScenarioSetup(scenarioInfo);
#line 134
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 135
            testRunner.When("user navigates to add pump supply order page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 136
            testRunner.Then("dropdown with id Order_ShippingMethod has Ground,Priority Overnight,2 Day,Express" +
                               ",Saturday Delivery,USPS", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
