// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TemplateProject.WebTests.Features
{
    using TechTalk.SpecFlow;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class OrderManagementDonorPumpSupplyFeature
    {

        private static TechTalk.SpecFlow.ITestRunner testRunner;

#line 1 "OrderManagementDonorPumpSupply.feature"
#line hidden

        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Order Management Donor Pump Supply", "\tIn order to manage Pump Supply orders\r\n\tAs a milk bank or warehouse user\r\n\tI wan" +
                    "t to be able to view, fulfill, verify, and print packing slips", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null)
                        && (testRunner.FeatureContext.FeatureInfo.Title != "Order Management Donor Pump Supply")))
            {
                TemplateProject.WebTests.Features.OrderManagementDonorPumpSupplyFeature.FeatureSetup(null);
            }
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }

        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }

        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.4.1 A table to show all Pump Supply Orders in any status for a donor")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order Management Donor Pump Supply")]
        public virtual void _5_4_1ATableToShowAllPumpSupplyOrdersInAnyStatusForADonor()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.4.1 A table to show all Pump Supply Orders in any status for a donor", ((string[])(null)));
#line 6
            this.ScenarioSetup(scenarioInfo);
#line 7
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
            testRunner.When("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
            testRunner.And("element with id pumpSupplyTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
            testRunner.Then("element pumpSupplyTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.4.2 An export feature to export the history view shall be added with current fi" +
            "lters")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order Management Donor Pump Supply")]
        public virtual void _5_4_2AnExportFeatureToExportTheHistoryViewShallBeAddedWithCurrentFilters()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.4.2 An export feature to export the history view shall be added with current fi" +
                    "lters", ((string[])(null)));
#line 12
            this.ScenarioSetup(scenarioInfo);
#line 13
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 14
            testRunner.When("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 15
            testRunner.And("element with id pumpSupplyTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
            testRunner.Then("element pumpSupplyTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 17
            testRunner.When("element with class k-grid-excel in element with id pumpOrdersGrid clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 18
            testRunner.Then("file with name Pump Supply Order Export was exported", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.4.3 User may also filter order table by every category except Donor Name and Ou" +
            "tgoing Tracking Number")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order Management Donor Pump Supply")]
        public virtual void _5_4_3UserMayAlsoFilterOrderTableByEveryCategoryExceptDonorNameAndOutgoingTrackingNumber()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.4.3 User may also filter order table by every category except Donor Name and Ou" +
                    "tgoing Tracking Number", ((string[])(null)));
#line 20
            this.ScenarioSetup(scenarioInfo);
#line 21
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 22
            testRunner.When("pump order created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 23
            testRunner.And("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 24
            testRunner.And("element with id pumpSupplyTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
            testRunner.Then("element pumpSupplyTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 26
            testRunner.When("filter 60002 in column DonorID in grid pumpOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 27
            testRunner.Then("the 2 column in 1 row in pumpOrdersGrid grid should be 60002", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 28
            testRunner.When("filter on grid pumpOrdersGrid is cleared", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 29
            testRunner.And("filter Tiny Treasures Milk Bank in column MilkBankName in grid pumpOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
            testRunner.Then("the 4 column in 1 row in pumpOrdersGrid grid should be Tiny Treasures Milk Bank", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 31
            testRunner.When("filter on grid pumpOrdersGrid is cleared", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 32
            testRunner.And("filter mbtsmbtester1 in column OrderBy in grid pumpOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
            testRunner.Then("the 9 column in 1 row in pumpOrdersGrid grid should be mbtsmbtester1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 34
            testRunner.When("filter on grid pumpOrdersGrid is cleared", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 35
            testRunner.And("filter Pending in column Status in grid pumpOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
            testRunner.Then("the 10 column in 1 row in pumpOrdersGrid grid should be Pending", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.4.4 User may filter “Bag Only” category by selecting “Yes”")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order Management Donor Pump Supply")]
        public virtual void _5_4_4UserMayFilterBagOnlyCategoryBySelectingYes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.4.4 User may filter “Bag Only” category by selecting “Yes”", ((string[])(null)));
#line 38
            this.ScenarioSetup(scenarioInfo);
#line 39
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 40
            testRunner.When("bag only order created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 41
            testRunner.When("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 42
            testRunner.And("element with id pumpSupplyTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 43
            testRunner.Then("element pumpSupplyTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 44
            testRunner.When("filter Yes in column BagOnlyName in grid pumpOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 45
            testRunner.Then("the 11 column in 1 row in pumpOrdersGrid grid should be Yes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.4.4.1 The printed Bag Packet will contain a Welcome Letter and Collecting Milk " +
            "for Donation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order Management Donor Pump Supply")]
        public virtual void _5_4_4_1ThePrintedBagPacketWillContainAWelcomeLetterAndCollectingMilkForDonation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.4.4.1 The printed Bag Packet will contain a Welcome Letter and Collecting Milk " +
                    "for Donation", ((string[])(null)));
#line 47
            this.ScenarioSetup(scenarioInfo);
#line 48
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 49
            testRunner.When("bag only order created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 50
            testRunner.When("bag only order created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 51
            testRunner.When("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 52
            testRunner.And("element with id pumpSupplyTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 53
            testRunner.Then("element pumpSupplyTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 54
            testRunner.When("filter Yes in column BagOnlyName in grid pumpOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 55
            testRunner.Then("the 11 column in 1 row in pumpOrdersGrid grid should be Yes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 56
            testRunner.When("row containing text Yes in grid pumpOrdersGrid is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 57
            testRunner.And("element with id printPackingSlips is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
            testRunner.And("switch to new tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
            testRunner.And("scroll to bottom of screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 60
            testRunner.Then("the page Order/PackingSlip should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.4.5 User has the option to filter by Pump Supply Order Statuses")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order Management Donor Pump Supply")]
        public virtual void _5_4_5UserHasTheOptionToFilterByPumpSupplyOrderStatuses()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.4.5 User has the option to filter by Pump Supply Order Statuses", ((string[])(null)));
#line 62
            this.ScenarioSetup(scenarioInfo);
#line 63
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 64
            testRunner.When("pump order created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 65
            testRunner.When("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 66
            testRunner.And("element with id pumpSupplyTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 67
            testRunner.Then("element pumpSupplyTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 68
            testRunner.When("filter Pending in column Status in grid pumpOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 69
            testRunner.Then("the 10 column in 1 row in pumpOrdersGrid grid should be Pending", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 73
            testRunner.When("pump order fulfilled 60002", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 74
            testRunner.And("filter OK in column Status in grid pumpOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 75
            testRunner.Then("the 10 column in 1 row in pumpOrdersGrid grid should be OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.4.6 A list of all Pump Supply orders shall include")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order Management Donor Pump Supply")]
        public virtual void _5_4_6AListOfAllPumpSupplyOrdersShallInclude()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.4.6 A list of all Pump Supply orders shall include", ((string[])(null)));
#line 77
            this.ScenarioSetup(scenarioInfo);
#line 78
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 79
            testRunner.When("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 80
            testRunner.And("element with id pumpSupplyTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 81
            testRunner.Then("element pumpSupplyTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 82
            testRunner.Then("the pumpOrdersGrid grid contains column Order #", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 83
            testRunner.Then("the pumpOrdersGrid grid contains column Donor ID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 84
            testRunner.Then("the pumpOrdersGrid grid contains column Milk Bank Name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 85
            testRunner.Then("the pumpOrdersGrid grid contains column Order Date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 86
            testRunner.Then("the pumpOrdersGrid grid contains column Shipping Date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 87
            testRunner.Then("the pumpOrdersGrid grid contains column Out Tracking", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 88
            testRunner.Then("the pumpOrdersGrid grid contains column Return Date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 89
            testRunner.Then("the pumpOrdersGrid grid contains column Order By", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 90
            testRunner.Then("the pumpOrdersGrid grid contains column Status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 91
            testRunner.Then("the pumpOrdersGrid grid contains column Bag Only", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.4.6.10.1\tIf order is fulfilled, Donor ID, Return Tracking, and Pump Serial Numb" +
            "er cannot be edited")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order Management Donor Pump Supply")]
        public virtual void _5_4_6_10_1IfOrderIsFulfilledDonorIDReturnTrackingAndPumpSerialNumberCannotBeEdited()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.4.6.10.1\tIf order is fulfilled, Donor ID, Return Tracking, and Pump Serial Numb" +
                    "er cannot be edited", ((string[])(null)));
#line 93
            this.ScenarioSetup(scenarioInfo);
#line 94
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 95
            testRunner.When("pump order created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 96
            testRunner.When("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 97
            testRunner.And("pump order fulfilled 60002", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 98
            testRunner.And("element with id pumpSupplyTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 99
            testRunner.Then("element pumpSupplyTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 100
            testRunner.When("filter OK in column Status in grid pumpOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 101
            testRunner.And("element with class k-grid-Edit clicked in pumpOrdersGrid grid with row containing" +
                               " text OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 102
            testRunner.Then("the page Order/EditOrder should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 103
            testRunner.Then("element with id Order_DonorID has attribute readonly with value true", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 104
            testRunner.Then("element with id updateDonorInfo has attribute readonly with value true", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 105
            testRunner.Then("element with id MilkBank has attribute disabled with value true", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 106
            testRunner.Then("element with id FirstName has attribute readonly with value true", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 107
            testRunner.Then("element with id Street has attribute readonly with value true", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 108
            testRunner.Then("element with id City has attribute readonly with value true", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 109
            testRunner.Then("element with id State has attribute readonly with value true", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 110
            testRunner.Then("element with id ZipCode has attribute readonly with value true", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 111
            testRunner.Then("element with id Email has attribute readonly with value true", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 112
            testRunner.Then("element with id PhoneNumber has attribute readonly with value true", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 113
            testRunner.Then("element with id OutgoingTracking has attribute readonly with value true", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 114
            testRunner.Then("element with id ReturnTracking has attribute readonly with value true", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 115
            testRunner.Then("element with id PumpSerial has attribute readonly with value true", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.4.6.10.2\tUser can edit Donor ID name address email Milk Bank phone notes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order Management Donor Pump Supply")]
        public virtual void _5_4_6_10_2UserCanEditDonorIDNameAddressEmailMilkBankPhoneNotes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.4.6.10.2\tUser can edit Donor ID name address email Milk Bank phone notes", ((string[])(null)));
#line 117
            this.ScenarioSetup(scenarioInfo);
#line 118
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 119
            testRunner.When("pump order created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 120
            testRunner.And("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 121
            testRunner.And("element with id pumpSupplyTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 122
            testRunner.Then("element pumpSupplyTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 123
            testRunner.When("filter Pending in column Status in grid pumpOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 124
            testRunner.And("element with class k-grid-Edit clicked in pumpOrdersGrid grid with row containing" +
                               " text Pending", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 125
            testRunner.Then("the page Order/EditOrder should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 126
            testRunner.When("text 60002 entered in Order_DonorID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 127
            testRunner.And("element with id updateDonorInfo is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 128
            testRunner.Then("the dropdown MilkBank has selected value Tiny Treasures Milk Bank", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 129
            testRunner.Then("element with id FirstName has value Erin", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 130
            testRunner.Then("element with id LastName has value Povich", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 131
            testRunner.Then("element with id Street has value 309 Cimarron Valley Trail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 132
            testRunner.Then("element with id State has value MO", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 133
            testRunner.Then("element with id ZipCode has value 63385", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 134
            testRunner.Then("element with id Email has value erinpovich@yahoo.com", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 135
            testRunner.Then("element with id PhoneNumber has value (314)-803-6875", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 136
            testRunner.When("text Test Note Edit entered in Order_Notes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 137
            testRunner.Then("element with id Order_Notes has value Test Note Edit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 138
            testRunner.When("element with id btnUpdateOrder is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 139
            testRunner.Then("the page Order/OrderDetail should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 140
            testRunner.Then("element with id donorId has text 60002", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 141
            testRunner.Then("element with id milkBank has text Tiny Treasures Milk Bank", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 142
            testRunner.Then("element with id firstName has text Erin", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 143
            testRunner.Then("element with id lastName has text Povich", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 144
            testRunner.Then("element with id street has text 309 Cimarron Valley Trail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 145
            testRunner.Then("element with id state has text MO", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 146
            testRunner.Then("element with id zipCode has text 63385", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 147
            testRunner.Then("element with id email has text erinpovich@yahoo.com", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 148
            testRunner.Then("element with id phoneNumber has text (314)-803-6875", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 149
            testRunner.Then("element with id orderNotes has text Test Note Edit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.4.6.10.3\tThe user may edit supplies quantity in Pump Supply Order")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order Management Donor Pump Supply")]
        public virtual void _5_4_6_10_3TheUserMayEditSuppliesQuantityInPumpSupplyOrder()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.4.6.10.3\tThe user may edit supplies quantity in Pump Supply Order", ((string[])(null)));
#line 151
            this.ScenarioSetup(scenarioInfo);
#line 152
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 153
            testRunner.When("pump order created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 154
            testRunner.And("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 155
            testRunner.And("element with id pumpSupplyTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 156
            testRunner.Then("element pumpSupplyTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 157
            testRunner.When("filter Pending in column Status in grid pumpOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 158
            testRunner.And("element with class k-grid-Edit clicked in pumpOrdersGrid grid with row containing" +
                               " text Pending", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 159
            testRunner.Then("the page Order/EditOrder should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 160
            testRunner.When("value 2 entered in numeric with DoublePumpingKit id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 161
            testRunner.And("value 2 entered in numeric with 24mmBreastshields id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 162
            testRunner.And("value 2 entered in numeric with 27mmBreastshields id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 163
            testRunner.And("value 2 entered in numeric with 30mmBreastshields id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 164
            testRunner.And("value 2 entered in numeric with 8ozBottlesSet id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 165
            testRunner.And("value 2 entered in numeric with PersonalFitConnectors id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 166
            testRunner.And("value 2 entered in numeric with ValvesandMembranes id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 167
            testRunner.And("value 2 entered in numeric with Membranes id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 168
            testRunner.And("value 2 entered in numeric with Tubing id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 169
            testRunner.And("value 2 entered in numeric with Bags id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 170
            testRunner.And("value 2 entered in numeric with YellowBag id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 171
            testRunner.Then("numeric with id DoublePumpingKit has value 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 172
            testRunner.Then("numeric with id 24mmBreastshields has value 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 173
            testRunner.Then("numeric with id 27mmBreastshields has value 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 174
            testRunner.Then("numeric with id 30mmBreastshields has value 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 175
            testRunner.Then("numeric with id 8ozBottlesSet has value 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 176
            testRunner.Then("numeric with id PersonalFitConnectors has value 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 177
            testRunner.Then("numeric with id ValvesandMembranes has value 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 178
            testRunner.Then("numeric with id Membranes has value 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 179
            testRunner.Then("numeric with id Tubing has value 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 180
            testRunner.Then("numeric with id Bags has value 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 181
            testRunner.Then("numeric with id Tubing has value 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 182
            testRunner.Then("numeric with id YellowBag has value 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.4.6.10.5\tReplacement Tracking number can edited at any time")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order Management Donor Pump Supply")]
        public virtual void _5_4_6_10_5ReplacementTrackingNumberCanEditedAtAnyTime()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.4.6.10.5\tReplacement Tracking number can edited at any time", ((string[])(null)));
#line 186
            this.ScenarioSetup(scenarioInfo);
#line 187
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 188
            testRunner.When("pump order created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 189
            testRunner.And("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 190
            testRunner.And("element with id pumpSupplyTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 191
            testRunner.Then("element pumpSupplyTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 192
            testRunner.When("filter Pending in column Status in grid pumpOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 193
            testRunner.And("element with class k-grid-Edit clicked in pumpOrdersGrid grid with row containing" +
                               " text Pending", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 194
            testRunner.Then("the page Order/EditOrder should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 195
            testRunner.When("text 1223-3344-4455 entered in ReplacementTracking", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 196
            testRunner.Then("element with id ReplacementTracking has value 1223-3344-4455", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 197
            testRunner.When("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 198
            testRunner.And("pump order fulfilled 60002", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 199
            testRunner.And("element with id pumpSupplyTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 200
            testRunner.Then("element pumpSupplyTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 201
            testRunner.When("filter OK in column Status in grid pumpOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 202
            testRunner.And("element with class k-grid-Edit clicked in pumpOrdersGrid grid with row containing" +
                               " text OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 203
            testRunner.Then("the page Order/EditOrder should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 204
            testRunner.When("text 1223-3344-4455 entered in ReplacementTracking", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 205
            testRunner.Then("element with id ReplacementTracking has value 1223-3344-4455", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.4.7 More order information shall be available when the order is clicked on and " +
            "will contain the following information")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order Management Donor Pump Supply")]
        public virtual void _5_4_7MoreOrderInformationShallBeAvailableWhenTheOrderIsClickedOnAndWillContainTheFollowingInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.4.7 More order information shall be available when the order is clicked on and " +
                    "will contain the following information", ((string[])(null)));
#line 207
            this.ScenarioSetup(scenarioInfo);
#line 208
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 209
            testRunner.When("pump order created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 210
            testRunner.When("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 211
            testRunner.And("element with id pumpSupplyTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 212
            testRunner.Then("element pumpSupplyTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 213
            testRunner.When("element with class k-i-expand clicked in pumpOrdersGrid grid with row containing " +
                               "text No", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 214
            testRunner.Then("element with class orders is visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.4.7.1 Order Items")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order Management Donor Pump Supply")]
        public virtual void _5_4_7_1OrderItems()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.4.7.1 Order Items", ((string[])(null)));
#line 216
            this.ScenarioSetup(scenarioInfo);
#line 217
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 218
            testRunner.When("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 219
            testRunner.And("element with id pumpSupplyTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 220
            testRunner.Then("element pumpSupplyTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 221
            testRunner.When("element with class k-i-expand clicked in pumpOrdersGrid grid with row containing " +
                               "text No", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 222
            testRunner.Then("element with class orders is visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.4.7.2 Shipping Information")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order Management Donor Pump Supply")]
        public virtual void _5_4_7_2ShippingInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.4.7.2 Shipping Information", ((string[])(null)));
#line 224
            this.ScenarioSetup(scenarioInfo);
#line 225
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 226
            testRunner.When("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 227
            testRunner.And("element with id pumpSupplyTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 228
            testRunner.Then("element pumpSupplyTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 229
            testRunner.When("element with class k-i-expand clicked in pumpOrdersGrid grid with row containing " +
                               "text No", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 230
            testRunner.Then("element with class orders is visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 231
            testRunner.When("element with id PumpShippingTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 232
            testRunner.Then("element PumpShippingTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("5.4.7.3 Print Packing Slip will contain the following")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order Management Donor Pump Supply")]
        public virtual void _5_4_7_3PrintPackingSlipWillContainTheFollowing()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5.4.7.3 Print Packing Slip will contain the following", ((string[])(null)));
#line 234
            this.ScenarioSetup(scenarioInfo);
#line 235
            testRunner.Given("Username MbtsMbTester1 logged in with password Prolacta99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 236
            testRunner.When("pump order created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 237
            testRunner.When("user navigates to Order Management", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 238
            testRunner.And("element with id pumpSupplyTab is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 239
            testRunner.Then("element pumpSupplyTab has class k-state-active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 240
            testRunner.When("filter No in column BagOnlyName in grid pumpOrdersGrid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 241
            testRunner.Then("the 11 column in 1 row in pumpOrdersGrid grid should be No", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 242
            testRunner.When("row containing text No in grid pumpOrdersGrid is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 243
            testRunner.And("element with id printPackingSlips is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 244
            testRunner.And("switch to new tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 245
            testRunner.Then("the page Order/PackingSlip should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
